### ISSUE TITLE
Run Tutorial RT(s) to check they are working

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#36]
## Description
Step four to prepare for UFS Coastal/NUOPC Walkthrough on March 1. 

## Solution
Need to run the RT(s) for the tutorial and confirm they are working. 

## Related to 
Follows #33, #34, #35

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 @saeed-moghimi-noaa I could able to run ufs-coastal RT on Frontera. I have just tested DATM+ROMS at this point and it seems it is working. I still need to clean the implementation and finalize the spack-stack installation since I have still couple of minor issues but I think we are in a good shape at this point. I'll keep you updated.

**Comment by uturuncoglu** [comment]
@pvelissariou1 Once it is ready to test, I'll let you know and you could test as an external user to see what happens. If we have any issue we could fix in that time.

**Comment by pvelissariou1** [comment]
@uturuncoglu Well this is going very fast, and I thank you very much. I will be able to test/help pretty soon.

**Comment by janahaddad** [comment]
successfully ran the coastal_ike_shinnecock_atm2sch case on Hera, with @pvelissariou1 's help (thank you!) 

Note that an initial attempt using ```./rt.sh -l rt_coastal.conf -a nems -k -n coastal_ike_shinnecock_atm2sch2ww3 intel``` failed because it could not find the baseline directory. On second attempt, ran successfully with `-c` option to create new baseline results

**Comment by janahaddad** [comment]
closing & tracking in https://github.com/oceanmodeling/ufs-coastal/issues/43 instead
