### ISSUE TITLE
Update License of ufs-coastal

### ISSUE THREAD

**Issue by pvelissariou1** [oceanmodeling/ufs-weather-model#56]
This issue is for the license file in UFS-Coastal. The file was derived from UFS Weather Model and includes the licenses of the model components in UFS-Coastal that are not in public domain. The file is in google drive (google doc). 
Items to check:
- Wording
- NOAA/CSDL license wording/requirements

**Comment by pvelissariou1** [comment]
@saeed-moghimi-noaa, @janahaddad, @SorooshMani-NOAA, @BahramKhazaei-NOAA, @yunfangsun, @AtiehAlipour-NOAA, @FariborzDaneshvar-NOAA Please take a look at the google doc I shared with you for suggestions/additions.

**Comment by saeed-moghimi-noaa** [comment]
Hi @pvelissariou1 and @uturuncoglu  

We need some level of customization to Readme and other files (e.g. Doc folder). It might make sense to discuss this next time at the UFS-weather meeting with Jun and others. 

Thanks,
-Saeed

**Comment by pvelissariou1** [comment]
@saeed-moghimi-noaa , @uturuncoglu Thank you Saeed, it is a good idea to bring it with June, I'll put it on the agenda as well. Other issues like build process, workflow, model components (HYCOM, MOM, ... that should not be part of UFS-Coastal ) should be addressed as well. Anyway just my random thoughts. @janahaddad has already recorded all these from our previous discussions and she will bring them up soon for discussion.

**Comment by uturuncoglu** [comment]
@saeed-moghimi-noaa @janahaddad @pvelissariou1 Yes, it would be nice to have discussion about those and learn how other application handles similar issues. I think it is always better to follow the conventions that are already in place. As I know other applications are handling documentation in the app level rather than modifying doc in the model level. We could have similar and isolate the changes like that. I am not sure about license, we could also have top level license in the app and maybe another one in the model. If you look at the license file in https://github.com/ufs-community/ufs-weather-model/blob/develop/LICENSE.md the test is very generic and they have list of components. So, we could add ours additionally to that.

**Comment by saeed-moghimi-noaa** [comment]
Hi @uturuncoglu 

I agree. Also as mentioned by Derrick we want to have domain specific information in ufs-coastal. This is important for our community and leadership. I am sure there are ways to do that. in particular for a specific files and folders (e.g. Readme and Doc)

**Comment by janahaddad** [comment]
See NOAA GH usage guidelines from 2017: https://drive.google.com/file/d/1GIbd-91a8B99GFLFAz8Sy9nCBtOW9Bzh/view?usp=drive_link

**Comment by janahaddad** [comment]
done at ufs-coastal-app repo
